deleted AddIdentity copy
Deleted Copy of AddIdentity Service register, because it reason to this exception
System.InvalidOperationException: 'Scheme already exists: Identity.Application'